version: '3.4'

services:
    board.host.api:
        image: ${DOCKER_REGISTRY-}boardhostapi
        build:
            context: .
            dockerfile: src/Board/Host/Board.Host.Api/Dockerfile
        ports:
            - 5000:80
            - 10000:443
        depends_on:
            - postgres

    filestorage.host.server:
        image: ${DOCKER_REGISTRY-}filestoragehostserver
        build:
            context: .
            dockerfile: src/FileStorage/Host/FileStorage.Host.Server/Dockerfile
        ports:
            - 5001:80
            - 10001:443
    
    identity.host.server:
        image: ${DOCKER_REGISTRY-}identityhostserver
        build:
            context: .
            dockerfile: src/Identity/Host/Identity.Host.Server/Dockerfile
        ports:
            - 5002:80
            - 10002:443

    notifier.host.consumer:
        image: ${DOCKER_REGISTRY-}notifierhostconsumer
        build:
            context: .
            dockerfile: src/Notifier/Host/Notifier.Host.Consumer/Dockerfile
        ports:
            - 5003:80
            - 10003:443

    postgres:
        image: "postgres"
        restart: always
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_DB=Board
            - POSTGRES_PASSWORD=postgres
        ports:
            - "5432:5432"
        volumes:
            - pg_volume:/var/lib/postgresql/solarvito

    minio:
        image: minio/minio:RELEASE.2022-11-26T22-43-32Z
        command: server --console-address ":9001" /data/
        ports:
            - "9000:9000"
            - "9001:9001"
            - "9090:9090"
        environment:
            MINIO_ROOT_USER: solarvito
            MINIO_ROOT_PASSWORD: solarvito123

    rabbitmq:
        image: rabbitmq:3.11-management
        container_name: rabbitmq
        environment:
            - RABBITMQ_DEFAULT_USER=guest
            - RABBITMQ_DEFAULT_PASS=guest
        ports:
            - "5672:5672"
            - "15672:15672"

    seq:
        image: datalust/seq:latest
        restart: unless-stopped
        environment:
          - ACCEPT_EULA=Y
        ports:
          - "5345:80"
          - "5341:5341"
        volumes:
          - seq-logs:/data
    
    cache:
        image: redis:6.2-alpine
        environment:
          - ALLOW_EMPTY_PASSWORD=yes
        restart: always
        ports:
          - '6379:6379'
        volumes: 
          - cache:/data

volumes:
    pg_volume:
    cache:
    seq-logs:


    
